// <auto-generated />
using System;
using System.Collections.Generic;
using Gamification.Infrastructure.DatabaseService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gamification.Infrastructure.Migrations
{
    [DbContext(typeof(ProductivityDbContext))]
    [Migration("20251105075440_ProductivityLogTable")]
    partial class ProductivityLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gamification.Core.GameModels.Achievement", b =>
                {
                    b.Property<string>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("achievement_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("ResetTime")
                        .HasColumnType("integer")
                        .HasColumnName("reset_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("AchievementId")
                        .HasName("pk_achievements");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_achievements_key");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("Gamification.Core.GameModels.GameStat", b =>
                {
                    b.Property<string>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("stat_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Coin")
                        .HasColumnType("integer")
                        .HasColumnName("coin");

                    b.Property<int>("DailyStreakCount")
                        .HasColumnType("integer")
                        .HasColumnName("daily_streak_count");

                    b.Property<float>("ExperiencePoints")
                        .HasColumnType("real")
                        .HasColumnName("experience_points");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("ProductivityMetrics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("productivity_metrics");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("WeeklyStreakCount")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_streak_count");

                    b.HasKey("StatId")
                        .HasName("pk_game_stats");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_game_stats_user_id");

                    b.ToTable("game_stats", (string)null);
                });

            modelBuilder.Entity("Gamification.Core.GameModels.UserAchievement", b =>
                {
                    b.Property<string>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("user_achievement_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AchievementId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("UserAchievementId")
                        .HasName("pk_user_achievements");

                    b.HasIndex("AchievementId")
                        .HasDatabaseName("ix_user_achievements_achievement_id");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_achievements_user_id_achievement_id");

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("Gamification.Core.Models.AnalysisResult", b =>
                {
                    b.Property<string>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("analysis_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<List<string>>("Category")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("category");

                    b.Property<int>("IntrinsicScore")
                        .HasColumnType("integer")
                        .HasColumnName("intrinsic_score");

                    b.Property<float>("RelevanceScore")
                        .HasColumnType("real")
                        .HasColumnName("relevance_score");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_id");

                    b.Property<string>("UserGoal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_goal");

                    b.HasKey("AnalysisId")
                        .HasName("pk_analysis_results");

                    b.HasIndex("SiteId", "UserGoal")
                        .IsUnique()
                        .HasDatabaseName("ix_analysis_results_site_id_user_goal");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("Gamification.Core.Models.ProductivityLog", b =>
                {
                    b.Property<string>("ProductivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("productivity_log_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("log_date");

                    b.Property<TimeSpan>("ProductiveTime")
                        .HasColumnType("interval")
                        .HasColumnName("productive_time");

                    b.Property<TimeSpan>("UnproductiveTime")
                        .HasColumnType("interval")
                        .HasColumnName("unproductive_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("ProductivityLogId")
                        .HasName("pk_productivity_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_productivity_logs_user_id");

                    b.ToTable("productivity_logs", (string)null);
                });

            modelBuilder.Entity("Gamification.Core.Models.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("site_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("SiteId")
                        .HasName("pk_sites");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_url");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("Gamification.Core.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<TimeSpan>("DailyTargetHours")
                        .HasColumnType("interval")
                        .HasColumnName("daily_target_hours");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Goal")
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Gamification.Core.Models.UserSiteVisit", b =>
                {
                    b.Property<string>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("visit_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnalysisId")
                        .HasColumnType("text")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("SiteId")
                        .HasColumnType("text")
                        .HasColumnName("site_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VisitEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_end_date");

                    b.Property<DateTime>("VisitStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_start_date");

                    b.HasKey("VisitId")
                        .HasName("pk_user_site_visits");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_user_site_visits_analysis_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_user_site_visits_processed_at")
                        .HasFilter("\"processed_at\" IS NULL");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_user_site_visits_site_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_site_visits_user_id");

                    b.HasIndex("VisitStartDate")
                        .HasDatabaseName("ix_user_site_visits_visit_start_date");

                    b.ToTable("user_site_visits", (string)null);
                });

            modelBuilder.Entity("Gamification.Core.GameModels.GameStat", b =>
                {
                    b.HasOne("Gamification.Core.Models.User", "User")
                        .WithOne("GameStat")
                        .HasForeignKey("Gamification.Core.GameModels.GameStat", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_stats_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gamification.Core.GameModels.UserAchievement", b =>
                {
                    b.HasOne("Gamification.Core.GameModels.Achievement", "Achievement")
                        .WithMany("AchievedUsers")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_achievements_achievement_id");

                    b.HasOne("Gamification.Core.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_users_user_id");

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gamification.Core.Models.AnalysisResult", b =>
                {
                    b.HasOne("Gamification.Core.Models.Site", "Site")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_results_sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Gamification.Core.Models.ProductivityLog", b =>
                {
                    b.HasOne("Gamification.Core.Models.User", "User")
                        .WithMany("ProductivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productivity_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gamification.Core.Models.UserSiteVisit", b =>
                {
                    b.HasOne("Gamification.Core.Models.AnalysisResult", "Analysis")
                        .WithMany("UserSiteVisit")
                        .HasForeignKey("AnalysisId")
                        .HasConstraintName("fk_user_site_visits_analysis_results_analysis_id");

                    b.HasOne("Gamification.Core.Models.Site", "Site")
                        .WithMany("UserSiteVisits")
                        .HasForeignKey("SiteId")
                        .HasConstraintName("fk_user_site_visits_sites_site_id");

                    b.HasOne("Gamification.Core.Models.User", "User")
                        .WithMany("UserSiteVisits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_site_visits_users_user_id");

                    b.Navigation("Analysis");

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gamification.Core.GameModels.Achievement", b =>
                {
                    b.Navigation("AchievedUsers");
                });

            modelBuilder.Entity("Gamification.Core.Models.AnalysisResult", b =>
                {
                    b.Navigation("UserSiteVisit");
                });

            modelBuilder.Entity("Gamification.Core.Models.Site", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("UserSiteVisits");
                });

            modelBuilder.Entity("Gamification.Core.Models.User", b =>
                {
                    b.Navigation("GameStat")
                        .IsRequired();

                    b.Navigation("ProductivityLogs");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserSiteVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
